client:
  url: http://localhost:4200

server:
  port: 8080

logging:
  level:
    root: DEBUG
bcrypt:
  log-rounds: 10

spring:
  application:
    name: RentalMovie
  output:
    ansi:
      enabled: DETECT
  data:
    mongodb:
      uri: mongodb+srv://tttn_movie_rental:UMcpzMNABJDkaAxN@clustermovierental.us7bvrr.mongodb.net/?retryWrites=true&w=majority&appName=ClusterMovieRental
      database: dbdev
  jwt:
    rsa:
      private-key: classpath:certs/private.pem
      public-key: classpath:certs/public.pem
    expiresTime: 7
  cookie:
    expiresTime: 7
  cloudinary:
    cloudName: dgpfsipnc
    apiKey: 952137373237171
    apiSecret: NJNsEwk5DtIBOa1eA-uc3l87_gM
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 953038709709-sockq7q23pe04qi21nsq2icqiq9v0esd.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  mail:
    verify:
      expire-time: 5
    host: smtp.gmail.com
    port: 587
    username: rentalmovie68@gmail.com
    password: whzrdggnyfwerkwe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
open:
  api:
    title: Tài liệu API Thuê Phim
    version: v1.0.0
    description: Tài liệu API cho ứng dụng thuê phim
    local-server-url: http://localhost:8080
    host-server-url: https://hoctuancustomservice.io.vn

