server:
  port: 8080

logging:
  level:
    root: DEBUG

spring:
  application:
    name: RentalMovie
  output:
    ansi:
      enabled: DETECT
  data:
    mongodb:
      uri: mongodb+srv://tttn_movie_rental:UMcpzMNABJDkaAxN@clustermovierental.us7bvrr.mongodb.net/?retryWrites=true&w=majority&appName=ClusterMovieRental
      database: dbdev

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
open:
  api:
    title: Tài liệu API Thuê Phim
    version: v1.0.0
    description: Tài liệu API cho ứng dụng thuê phim
    local-server-url: http://localhost:8080
    host-server-url: https://hoctuancustomservice.io.vn

