server:
  port: 8080

logging:
  level:
    root: DEBUG

spring:
  application:
    name: RentalMovie
  output:
    ansi:
      enabled: DETECT

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
